### PR TITLE
Add GH Action Super Linter

### PR DESCRIPTION
**Pull request by WSLUser**
This uses the templates from https://github.com/github/super-linter/tree/master/TEMPLATES currently. A future PR can add the necessary templates to the Fedira Remix repository and update the source of Templates following the README. Additionally we can add flags to explicitly choose the linters applicable to this code base.

### CODE REVIEW

**Comment by WSLUser** [comment]
Don't know why but should show up like it does here: https://github.com/WSLUser/Fedora-Remix-for-WSL/pull/1

**Comment by WSLUser** [comment]
@crramirez Can you check if you've authorized GH Actions for WhitewaterFoundry repos. I think this is the issue I've been running into.

**Comment by crramirez** [comment]
I think they are enabled: 
image

**Comment by WSLUser** [comment]
I think we should just add this in. I'm not sure why it's not showing here but maybe after merge, it'll start showing up. There's nothing more I can do to get this to work as it shows up perfectly in my fork. Maybe it's an account permission,not a repo issue. The account itself also has to authorize GH actions. From there you can choose which repos accept them and which ones don't as your screenshot above shows.

**Pull request merged**
